### ISSUE TITLE
Could this tool work on H268N?

### ISSUE THREAD

**Issue by crafter999** [sta-c0000/tpconf_bin_xml#1]
I have a router named ZTE ZXHN H268N that has pretty much the same specs with TD-W9970 and \*I think\* it uses the same config files for upload/backup settings but I get the following error:
```
ERROR: Wrong input file type!
```
You can download the bin file from this link below and check out if there are any similarities and if it's possible to make it work with at least one or two lines of code or something I would be grateful.  If it's pain in the butt, just leave it. 

https://mega.nz/#!DmglXZaY!Pqc8kDHMaRw0C7Pm__RSH0Wu8CZLhsKnpJgEgzDfmYs

**Comment by sta-c0000** [comment]
This tool (tpconf_bin_xml.py) is meant to handle TP-Link’s customized compression and encryption key to convert .bin <=> .xml configuration files.  Although it is possible that another TP-Link model may utilize the same compression and encryption key, it’s unlikely that another manufacturer would.  As you may have already determined despite the generic error message you received, it appears that config file was not DES encrypted.  Sorry for delayed response but thanks for closing.

**Comment by streetster** [comment]
@crafter999 did you ever manage to decrypt your config file? If not, any case you could upload it and I'll take a look?
