### ISSUE TITLE
Support for TD-W8980

### ISSUE THREAD

**Issue by hobi82** [sta-c0000/tpconf_bin_xml#11]
At the moment tpconf_bin_xml.py is capable to decrypt/decompress the conf.bin file coming from a TP-LINK TD-W8980 v.1(.2) but it can't seem to create a W8980 supported .bin file after changes have been added to the .xml or even just without any changes at all. 

My current workaround is to create a .bin file from my changed/unchanged conf.xml via the 3rd-party tool StatPOSTer-20160306.jar and with selecting W9980 in there as the device for the encryption process. This then creates an seemingly uncompressed (much bigger) conf.bin file. This file then seems actually compatible with the W8980 router. The router accepts the restore and reboots with .bin files created that (Frankenstein) way.

It would be nice-to-have added support for the TD-W8980 directly within tpconf_bin_xml.py, so no extra tool is needed to re-encrypt the .xml files into working .bin's. Maybe even without using the compression at all (since the router seems not requesting it).

**Comment by sta-c0000** [comment]
I've just changed it to look for 'W8980' in the XML as well.  I don't have a W8980 to test, I'm just assuming, let me know if it works.  Thanks!

**Comment by Lokotito** [comment]
IF anyone is interested, works fine with w9980 (tested with telnet in port 1023 injection)

Thanks.
