### ISSUE TITLE
Support for TD-W9960

### ISSUE THREAD

**Issue by minanagehsalalma** [sta-c0000/tpconf_bin_xml#13]
@sta-c0000  the file can be decrypted using router pass view.
![image](https://user-images.githubusercontent.com/20546638/102701518-71e41a00-4260-11eb-9514-c8653af5f803.png)

how can i encrypt it back?

also the decryption using 
`openssl enc -d -des-ecb -nopad -K 478DA50BF9E3D2CF -in conf.bin -out newnew.xml
`
gives me this non sense
![image](https://user-images.githubusercontent.com/20546638/102701506-4d883d80-4260-11eb-9368-c61a018eebc9.png)

**the config file**

[conf.zip](https://github.com/sta-c0000/tpconf_bin_xml/files/5720272/conf.zip)

**Comment by minanagehsalalma** [comment]
oh it works ... thanks a lot.

**Comment by sta-c0000** [comment]
> Is there a way to make sshd work on TD-W9960?(since it doesn't have a USB port) Also is there a tutorial on how to flash a firmware back if things go south?

Unlikely you can use sshd without a USB drive connected.  Even if you could place a complex script inside the XML Description field (and you can to some degree), fetching the sshd binary from the network into a ramdisk and executing it from there would strain the device's RAM.
BTW **tpconf_bin_xml.py** does not modify the firmware at all, only the router settings.
