### ISSUE TITLE
Encryption does not work on TD-W8970

### ISSUE THREAD

**Issue by w8970** [sta-c0000/tpconf_bin_xml#16]
HW: TP Link TD-W8970B V1

Decryption from conf.bin to conf.xml works fine.
After changing conf.xml and encrypt it back to conf_new.bin the router does not accept the file, after upload comes:
Error, wrong format, Error code: 4501.

Please find a patch to fix this. (Tested on my own device.)
[tpconf_bin_xml.W8970.patch.txt](https://github.com/sta-c0000/tpconf_bin_xml/files/6704704/tpconf_bin_xml.W8970.patch.txt)

**Comment by sta-c0000** [comment]
Patch applied, Thanks!
