### ISSUE TITLE
When Try to Run busybox-mips permission denied on /tmp Directory

### ISSUE THREAD

**Issue by kies83** [sta-c0000/tpconf_bin_xml#18]
I am facing an issue on router . With busybox version is 1.17.2 it doesn't have chmod command to give file execute permission. I want to create a firmware backup.bin. i have downloaded busybox binaries and then uploaded to router /tmp folder and when we run ./busybox-mips permission denied  sh..   shows error. 

Help me to figure out this error..
@sta-c0000 @d3dave @the-dem

**Comment by sta-c0000** [comment]
Sorry, I'll close this as it does not appear to relate to this project: **_tpconf_bin_xml.py_** functionality.

But also you don't mention which TP-Link model you have; find out what CPU architecture yours uses to ensure you are using a correct version of the busybox binary.  Different models have different CPU architectures, it could be any of: mips (big endian) mipsel (little endian), ARM, etc.

I've updated the README in an attempt to clarify this.
