### ISSUE TITLE
I've created a web editor adapted from this script.

### ISSUE THREAD

**Issue by jahed** [sta-c0000/tpconf_bin_xml#22]
Hi @sta-c0000. Firstly, thank you so much for writing this script! It's helped me a lot.

I've ported the code over to JavaScript and it's available as a client-side web page. This will allow anyone to edit their config without needing to install Python or run a script from terminal.

https://jahed.github.io/tp-link-config-editor/

Not all of the various features and models have been ported yet as I don't have config files to test with, but that should be simple to do in the future.

Apologies in advance for using the issue tracker to share this, there's no other channels to contact you. I thought I'd let you know as it's adapted from your work.

I also suggest adding a LICENSE to your repository so people know what we can/can't do with your work. https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

Thanks again!

**Comment by sta-c0000** [comment]
That's really neat.

(thanks for tip; source code has GPL3 in header since start)
