### ISSUE TITLE
TP-Link TD-W9970 V2

### ISSUE THREAD

**Issue by txr660** [sta-c0000/tpconf_bin_xml#4]
Hi
I have bought the TP-Link TD-W9970 V2 Router last week , and I was surprised to find that the LEDs for
LAN or WiFi don't flash or blink . I actually considered returning it , but it's my only option right now .

I'm very new to BusyBox / Bash ( but I can manage my computer easily if I find instructions )

So , I have 2 questions I hope you can help with : 

1- How to control the LEDs ? Where to put the command you wrote in the Readme.md ?
There is a BusyBox file called >> busybox_PRINTF << that I downloaded from the website but I don't
where to use . 

2- I have a VDSL connection and I know I can't install OpenWRT ( like you pointed ) because there are no
OSS drivers . But I like the availability of adblocker packages with OpenWRT .

So , is there a way to do this with BusyBox or other scripts that I put in a USB drive and use with the
router ?

Thank you

**Comment by sta-c0000** [comment]
1 -
Busybox is a multi-call binary... so a printf symbolic link to busybox-mips will work (`ln -s /var/usbdisk/sda1/busybox-mips /var/bin/printf`), or simply `busybox-mips printf` will work; an alias would also work, as shown in the _readme_.
I mentioned in the _readme_ that you can control the LEDs from your **own** scripts or programs.  If you are asking me how to get the LEDs to flash whenever there is network traffic... unfortunately you can’t (not without a lot of overhead anyhow).  TP-Link would have had to include the netfilter (_iptables_) led module and system class for their kernel, which they did not do.

2 -
Possibly, but you probably would need more than busybox.  You might be able to run a __dnsmasq__ service on the router configured with publicly available blocklists (after killing the built in dnsProxy service)... (this would require a static MIPS dnsmasq which could be created using Buildroot).

But it would probably be much simpler for you to run something like Pi-hole on a another (cheap) device on your network.

Have fun and good luck.
