### ISSUE TITLE
Encrypt conf for W9980B

### ISSUE THREAD

**Issue by puresoul** [sta-c0000/tpconf_bin_xml#8]
Hi,

decrypt works fine, but if I encrypt config and try upload it on my router it returns 

Error code: 4501

You put a wrong file.

I try it with/without -l and same problem, have your script already support for that?

**Comment by sta-c0000** [comment]
Hi, sorry for the delay.  @d3dave recently added [support for decompressing W9980 conf](https://github.com/sta-c0000/tpconf_bin_xml/pull/5).  Indeed, right now the code only encrypts & compresses for W9970.  I don't have access to a W9980 to test, but it should be fairly straightforward to add; I'll look at adding a command line option for the W9980 (hashing, compressing and encrypting) some time later.  Thanks.

**Comment by puresoul** [comment]
I'm willing to help you with that, but because i got no insight how that process may looks like I can for now just only test it on my device...

**Comment by sta-c0000** [comment]
I applied a fix, but I'm just guessing... no need for a command line option after all, it should just work.
Let me know if it works.
Thank for the issue and for testing the fix.

**Comment by puresoul** [comment]
ok, nice work. Works great
